# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6e271294c67762ab317f61f88adc59a5530176d8a633ee64ec51bf6c06dc14cc3c669e9ad4a05e3ca749cacdda5d4936655d192ec5a752ce0ae7043cba40d3c

test:
  secret_key_base: 1b0f113395f4edcfdaaa5b1fb056b47b5491c3bfe9376d06008dd6ae349a9cbbc985987334c5ab7a595c560c8b3612bbe8844d48bf71b59b25bb7e15fc0e59ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
